### ISSUE TITLE
New task starts from int value 2.

### ISSUE THREAD

**Issue by Sounak008** [HxX2/todocli#5]
When I create a task when the todo list is empty, it starts from 2. When I do `todo -r 1` , it fixes the issue. Please look into it.
![image](https://github.com/user-attachments/assets/85c6e972-6ce7-4323-a4c3-cad35ae7c639)

**Comment by Sounak008** [comment]
The issue of an extra empty line being added to your file when tasks are appended might be due to the way you're writing tasks to the file. Specifically, when you use `fmt.Sprintf("\n[] %s", task)` in the `AddTask` method, it prepends a newline character before the task text, which creates an extra blank line at the top if it's the first line added to the file.

To fix this, you should avoid adding the leading newline character when the file is empty. Here’s how you can adjust the `AddTask` method to handle this:

### Updated `AddTask` Method

```go
func (t Todo) AddTask(task string) {
    var ftask string
    // Check if the file is empty
    file, err := os.Open(t.filePath)
    if err != nil {
        pprint.Error(fmt.Sprintf("Can't open file %s\n", t.filePath))
        return
    }
    defer file.Close()

    stat, err := file.Stat()
    if err != nil {
        pprint.Error(fmt.Sprintf("Can't get file stats %s\n", t.filePath))
        return
    }

    // If file is empty, do not prepend a newline
    if stat.Size() == 0 {
        ftask = fmt.Sprintf("[] %s", task)
    } else {
        ftask = fmt.Sprintf("\n[] %s", task)
    }

    file.Close() // Close the file before writing
    err = file.Write(t.filePath, ftask, os.O_APPEND)
    if err != nil {
        pprint.Error(fmt.Sprintf("Can't write to file %s\n", t.filePath))
        return
    }

    t.PrintList()
}
```

### Key Changes:

1. **Check File Size**: Before adding a task, check if the file is empty by using `os.Stat()` to get the file size. If the file size is 0, don't prepend a newline character; otherwise, prepend a newline character to separate tasks.

2. **Error Handling**: Ensure that any errors encountered while checking file stats or writing to the file are handled properly and reported.

### Additional Considerations:

- **Ensure File Closure**: Make sure that the file is closed before writing and re-opening the file for checking its size.
- **Avoid Extra Newlines**: By conditionally adding the newline character based on the file size, you can avoid inserting an extra newline at the beginning of the file.

With these changes, your `AddTask` method should handle the file correctly without adding an unnecessary empty line at the top.



### ^ This answer was generated by ChatGPT when I gave it the op.go file. See if it helps.

**Comment by HxX2** [comment]
Thanks i will fix it ASAP
